### ISSUE TITLE
Service with rpc's fail generating

### ISSUE THREAD

**Issue by PhilipMantrov** [Means88/tsbuf#1]
```
undefined:5199
      throw peg$buildStructuredError(
      ^
SyntaxError: Expected "/*", "//", "}", end of line, or whitespace but "r" found.
    at peg$buildStructuredError (eval at compile (C:\git\grpc-microservices\evodesk-grpc\node_modules\pegjs\lib\compiler\index.js:67:29), <anonymous>:657:14)
    at Object.peg$parse [as parse] (eval at compile (C:\git\grpc-microservices\evodesk-grpc\node_modules\pegjs\lib\compiler\index.js:67:29), <anonymous>:5199:13)
    at exportSingleFile (C:\git\grpc-microservices\evodesk-grpc\node_modules\tsbuf\dist\cli\exporter.js:59:31)
    at tsbuf (C:\git\grpc-microservices\evodesk-grpc\node_modules\tsbuf\tsbuf:33:5)
    at executeMe (C:\git\grpc-microservices\evodesk-grpc\node_modules\execute-me\lib\index.js:40:15)
    at Object.<anonymous> (C:\git\grpc-microservices\evodesk-grpc\node_modules\tsbuf\tsbuf:53:1)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
```

```
syntax = "proto3";
package EvodeskAuth;

service Auth {
    rpc SignJWT(SignJWTRequest) returns (SignJWTResponse) {} //failed on first char 'r'
    rpc VerifyJWT(JWTRequest) returns (VerifyJWTResponse) {}
}

message Error {
    int32 code = 1;
    string message = 2;
}

message Account {
    string _id = 1;
    string login = 2;
    string password = 3;
    string role = 4;
}

message SignJWTRequest {
    string login = 1;
    string password = 2;
}

message SignJWTResponse {
    string jwt = 1;
    Error error = 2;
}

message JWTRequest {
    string jwt = 1;
}

message VerifyJWTResponse {
    bool allow = 1;
    Error error = 2;
}

message JWTObject {
    Account account = 1;
}
```

**Comment by PhilipMantrov** [comment]
I finded another error with `string _id = 1;` and fix it by adding in protobuf.pegjs in `Letter` section `= [_A-Za-z]`

**Comment by PhilipMantrov** [comment]
Problem finded (and try fixed) 
```
ServiceBody
  = "{" body:(__ (Rpc / EmptyStatement) __)* "}" {
    return body;
  }
```
but after this fix new service interface dont appear in generated ts file.
